### ISSUE TITLE
Finalize Application

### ISSUE THREAD

**Issue by OutOfIdeasException** [OutOfIdeasException/halloween-trivia#3]
## Description
The core functionality of the application works, but I still have just under two weeks to submit so I'll add additional features. 

### Tasks
- [x] Disable "Info" button once "Start Game" is clicked to clear a bug which displays multiple elements if info is visible while the start animation completes
* Disable the button and re-enable when the replay function is called 
- [x] Prevent users from submitting no-answers
* Have an alert advising the user an option must be selected
* Make sure the buttons are still active until an option is selected
- [x] Make the application mobile friendly
* Add viewport to make the application mobile friendly
- [x] Add music
* Use trimmed down clips (30 seconds max)
* Add a control to enable / disable the music 
* Change music based on where the user is (begin, during game, end)
- [x] Add a feedback system
* Provide feedback to let the user know whether or not their current selection was correct or not, and describe why

**Comment by OutOfIdeasException** [comment]
Start, End, and Info Screen mobile friendly efforts are completed. I may redesign the answer layout for mobile and I'm flirting with some ideas.

**Comment by OutOfIdeasException** [comment]
Disabled both buttons when the animation plays. The app worked like this previously but I reset some things while working on the viewport. 

I am going to remove the table and add a grid to the answer area. On desktop, the questions should display the same that they always have but on mobile they should be stacked vertically.

**Comment by OutOfIdeasException** [comment]
Mobile friendly is working. The way it was set up, all I had to do was create a grid view for both the regular and mobile views. Removing the table actually improved the UI so no re-arranging was needed. The next step is the feedback system as it is the most labor intensive.

**Comment by OutOfIdeasException** [comment]
Feedback system implemented and tested.

**Comment by OutOfIdeasException** [comment]
Ran into some issues regarding preventing users from submitting non-values. Will revisit tomorrow.

**Comment by OutOfIdeasException** [comment]
Figured out the "blank answer" prevention system. It will require some changes but it's all manual work without much thought from here. Putting in some work tonight before bed and will resume tomorrow.

**Comment by OutOfIdeasException** [comment]
Rather than just adding music, certain sound bytes will play at certain parts of the game. I have the concept working and need to apply it to all aspects of the game. I should be able to turn this in by the end of the day Saturday.

**Comment by OutOfIdeasException** [comment]
Was able to understand a lot of my previous errors and streamlined finishing the project. Importing changes now. There are some minor things that can be improved but the entire project works after multiple checks.
